dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libboost-system-dev
      - valgrind
      - cppcheck

jobs:
  include:
    - stage: unittest
      script: CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 tools/unittest_valgrind.sh
    - stage: unittest
      script: CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 tools/unittest_asan.sh
    - stage: cpplint
      script: tools/cpplint.sh
    - stage: cppcheck
      script: tools/cppcheck.sh
