dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libboost-system-dev
      - valgrind

jobs:
  include:
    - stage: unittest_valgrind
      script: CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 tools/travis/unittest_valgrind.sh
    - stage: unittest_asan
      script: CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 tools/travis/unittest_asan.sh
